
CAKE

MASTERCHEF

MASTERCHEF_V2

CAKE_POOL

MasterchefV2: {
    Farm Pools <-> Regular Pool
    Farm Pools <-> Special Pool
}
SyrupPool: {
    Flexible Staking
    Fixed Term Staking
    Fixed Term Staking <-> deposit
    Flexible Staking <-> deposit
    deposit: deposit(uint256 _amount, uint256 _lockDuration)
    withdraw: withdraw(uint256 _shares)
}

# MasterchefV2.Farm Pools <-> SyrupPool.deposit
# MasterchefV2.Farm Pools <-> SyrupPool.withdraw


